### ISSUE TITLE
Point 1

### ISSUE THREAD

**Issue by chema9355** [chema9355/SpaiEcp2JoseMariaAguirre#1]
https://github.com/chema9355/SpaiEcp2JoseMariaAguirre/wiki/Point-1

**Comment by RaquelDiazG** [comment]
- He añadido una tercera coordenada al punto
- He modificado todos los métodos de la clase para que funcionen correctamente con una nueva coordenada (excepto phase que no he encontrado la formula) 
- He modificado los tests para que se adecuen a la clase con una nueva coordenada
- Todos los test han pasado correctamente, así que he mergeado la rama a develop
- Cierro el issue
